name: learn-github-actions
on: [push]
jobs:
  build-pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: apt-get update
      # - run: apt-get install -y pandoc
      # - run: pandoc 2021-11-22.md -s -t html -o 2021-11-22.html
      - run: touch hoge.txt
      - run: ls -la
      - run: git config --global user.name "tententen bot"
      - run: git config --global user.email "s@sudame.net"
      - run: git checkout -b pages
      - run: git add .
      - run: git commit -m 'tententen update'
      # - run: git remote set-url origin https://github.com:${GITHUB_TOKEN}@github.com/sudame/tententen.me.git
      # - run: git push origin pages
